django_and_folium/config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token



urlpatterns = [
    #path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", include("django_and_folium.geo_app.urls", namespace='geo_app')),
    path("seattle/", include("django_and_folium.seattle.urls", namespace='seattle')),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("django_and_folium.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

django_and_folium/django_and_folium/seattle/urls.py
from django.urls import path

from . import views

app_name = 'seattle'


urlpatterns = [
    # Main App Page
    path('', views.index, name='index'),

    # Importing Data
    path('import-hospitals-data/', views.import_hospitals_data, name='import-hospitals-data'),
    path('import-schools-data/', views.import_schools_data, name='import-schools-data'),
    path('import-libraries-data/', views.import_libraries_data, name='import-libraries-data'),

    # Exporting Data
    path('export-hospitals-data/', views.export_hospitals_data, name='export-hospitals-data'),
    path('export-schools-data/', views.export_schools_data, name='export-schools-data'),
    path('export-libraries-data/', views.export_libraries_data, name='export-libraries-data'),

]

django_and_folium/django_and_folium/seattle/models.py
from django.db import models


class Hospital(models.Model):
    """ Model Class represents each Hospital in Seattle """
    facility = models.CharField(max_length=250, null=True, default='test')
    address = models.CharField(max_length=250, null=True, default='test')
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    class Meta:
        verbose_name = "Hospital"
        verbose_name_plural = "Hospitals"

    def __str__(self):
        """Return string representation of the model"""
        return self.facility


class School(models.Model):
    """ Model class represents Public School in Seattle """
    name = models.CharField(max_length=250, null=True, default='test')
    address = models.CharField(max_length=250, null=True, default='test')
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    class Meta:
        verbose_name = "School"
        verbose_name_plural = "Schools"

    def __str__(self):
        """Return string representation of the model"""
        return self.name


class Library(models.Model):
    """Model class represents a Library in Seattle"""
    name = models.CharField(max_length=250, null=True, default='test')
    address = models.CharField(max_length=250, null=True, default='test')
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    class Meta:
        verbose_name = "Library"
        verbose_name_plural = "Libraries"

    def __str__(self):
        """Return string representation of the model"""
        return  self.name

django_and_folium/django_and_folium/seattle/views.py
import folium
from folium.plugins import MarkerCluster, Fullscreen, LocateControl, Geocoder

from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from django.contrib import messages

from tablib import Dataset

from .models import Hospital, School, Library
from .resources import HospitalResource, SchoolResource, LibraryResource


class HomePage(generic.TemplateView):
    """ Class used for displaying website's main page. """
    template_name = 'index.html'


def index(request):

    # Create folium basemap
    map = folium.Map(
        location=[47.6062100, -122.3320700],
        tiles='cartodbpositron',
        zoom_start=11,
        attr= 'Public Schools in Seattle'
    )

    # Add a second TileLayer to the basemap
    folium.TileLayer('cartodbdark_matter').add_to(map)


    # Add Schools Data
    schools = School.objects.all()

    schools_simple_markers = folium.FeatureGroup(name='Schools Simple Markers').add_to(map)

    for school in schools:
        locations = [school.latitude, school.longitude]
        folium.Marker(
            locations,
            icon=folium.Icon(icon = "graduation-cap", prefix='fa'),
            tooltip="School Name: " + str(school.name),
            popup="School Address :" + school.address,
    ).add_to(schools_simple_markers)

    schools_marker_cluster = folium.FeatureGroup(name='Schools Marker Cluster', show=False).add_to(map)

    marker_cluster = MarkerCluster()

    for school in schools:
        locations = [school.latitude, school.longitude]
        marker_cluster.add_child(
            folium.Marker(
                locations,
                icon=folium.Icon(icon = "graduation-cap", prefix='fa'),
                tooltip="School Name: " + str(school.name),
                popup="School Address :" + school.address,
            )
        ).add_to(schools_marker_cluster)

    ##################################################################################################

    # Add Libraries data:
    libraries = Library.objects.all()

    libraries_simple_markers = folium.FeatureGroup(name='Libraries Simple Markers', show=False).add_to(map)

    for library in libraries:
        locations = [library.latitude, library.longitude]
        folium.Marker(
            locations,
            icon=folium.Icon(icon = "book", prefix='fa'),
            tooltip="Library Name: " + str(library.name),
            popup="Library Address :" + library.address,
        ).add_to(libraries_simple_markers)

    libraries_marker_cluster = folium.FeatureGroup(name='Libraries Marker Cluster', show=False).add_to(map)

    marker_cluster = MarkerCluster()

    for library in libraries:
        locations = [library.latitude, library.longitude]
        marker_cluster.add_child(
            folium.Marker(
                locations,
                icon=folium.Icon(icon = "book", prefix='fa'),
                tooltip="Library Name: " + str(library.name),
                popup="Library Address :" + library.address,
            )
        ).add_to(libraries_marker_cluster)

    ##################################################################################################

    # Add Hospitals data
    hospitals = Hospital.objects.all()

    hospitals_simple_markers = folium.FeatureGroup(name='Hospitals Simple Markers', show=False).add_to(map)

    for hospital in hospitals:
        locations = [hospital.latitude, hospital.longitude]
        folium.Marker(
            locations,
            icon=folium.Icon(icon_color = "red", icon = "h-square", prefix='fa'),
            tooltip="Hospital Name: " + str(hospital.facility),
            popup="Hospital Address :" + hospital.address,
        ).add_to(hospitals_simple_markers)

    hospitals_marker_cluster = folium.FeatureGroup(name='Hospitals Marker Cluster', show=False).add_to(map)

    marker_cluster = MarkerCluster()

    for hospital in hospitals:
        locations = [hospital.latitude, hospital.longitude]
        marker_cluster.add_child(
            folium.Marker(
                locations,
                icon=folium.Icon(icon_color = "red", icon = "h-square", prefix='fa'),
                tooltip="Hospital Name: " + str(hospital.facility),
                popup="Hospital Address :" + hospital.address,
            )
        ).add_to(hospitals_marker_cluster)
    ##################################################################################################

    folium.LayerControl(position='bottomright').add_to(map)
    Fullscreen().add_to(map)
    LocateControl().add_to(map)
    Geocoder().add_to(map)
    folium.LatLngPopup().add_to(map)

    map = map._repr_html_()

    context = {
        'map': map
    }

    return render(request, 'map.html', context)

########################################################################################################


def import_hospitals_data(request):
    if request.method == 'POST':
        file_format = request.POST['file-format']
        hospital_resource = HospitalResource()
        dataset = Dataset()
        new_hospitals = request.FILES['importData']

        if file_format == 'CSV':
            imported_data = dataset.load(new_hospitals.read().decode('utf-8'),format='csv')
            result = hospital_resource.import_data(dataset, dry_run=True)

        elif file_format == 'JSON':
            imported_data = dataset.load(new_hospitals.read().decode('utf-8'),format='json')
            # Testing data import
            result = hospital_resource.import_data(dataset, dry_run=True)

        if not result.has_errors():
            # Import now
            hospital_resource.import_data(dataset, dry_run=False)
            messages.success(request, 'Data Imported Successfully.')

    return render(request, 'seattle/import_hospitals_data.html')



def export_hospitals_data(request):
    if request.method == 'POST':
        # Get selected option from form
        file_format = request.POST['file-format']
        hospital_resource = HospitalResource()
        dataset = hospital_resource.export()

        if file_format == 'CSV':
            response = HttpResponse(dataset.csv, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="seattle/data/hospitals.csv"'
            return response
        elif file_format == 'JSON':
            response = HttpResponse(dataset.json, content_type='application/json')
            response['Content-Disposition'] = 'attachment; filename="seattle/data/hospitals.json"'
            return response
        elif file_format == 'XLS (Excel)':
            response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename="seattle/data/hospitals.xls"'
            return response

    return render(request, 'seattle/export_hospitals_data.html')


def import_schools_data(request):
    if request.method == 'POST':
        file_format = request.POST['file-format']
        school_resource = SchoolResource()
        dataset = Dataset()
        new_schools = request.FILES['importData']

        if file_format == 'CSV':
            imported_data = dataset.load(new_schools.read().decode('utf-8'),format='csv')
            result = school_resource.import_data(dataset, dry_run=True)

        elif file_format == 'JSON':
            imported_data = dataset.load(new_schools.read().decode('utf-8'),format='json')
            # Testing data import
            result = school_resource.import_data(dataset, dry_run=True)

        if not result.has_errors():
            # Import now
            school_resource.import_data(dataset, dry_run=False)
            messages.success(request, 'Data Imported Successfully.')

    return render(request, 'seattle/import_schools_data.html')



def export_schools_data(request):
    if request.method == 'POST':
        # Get selected option from form
        file_format = request.POST['file-format']
        school_resource = SchoolResource()
        dataset = school_resource.export()

        if file_format == 'CSV':
            response = HttpResponse(dataset.csv, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="seattle/data/schools.csv"'
            return response
        elif file_format == 'JSON':
            response = HttpResponse(dataset.json, content_type='application/json')
            response['Content-Disposition'] = 'attachment; filename="seattle/data/schools.json"'
            return response
        elif file_format == 'XLS (Excel)':
            response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename="seattle/data/schools.xls"'
            return response

    return render(request, 'seattle/export_schools_data.html')



def import_libraries_data(request):
    if request.method == 'POST':
        file_format = request.POST['file-format']
        library_resource = LibraryResource()
        dataset = Dataset()
        new_libraries = request.FILES['importData']

        if file_format == 'CSV':
            imported_data = dataset.load(new_libraries.read().decode('utf-8'),format='csv')
            result = library_resource.import_data(dataset, dry_run=True)

        elif file_format == 'JSON':
            imported_data = dataset.load(new_libraries.read().decode('utf-8'),format='json')
            # Testing data import
            result = library_resource.import_data(dataset, dry_run=True)


        if not result.has_errors():
            # Import now
            library_resource.import_data(dataset, dry_run=False)
            messages.success(request, 'Data Imported Successfully.')


    return render(request, 'seattle/import_library_data.html')



def export_libraries_data(request):
    if request.method == 'POST':
        # Get selected option from form
        file_format = request.POST['file-format']

django_and_folium/django_and_folium/seattle/templates/seattle/export_hospitals_data.html
{% extends 'base.html' %}

{% block title %}Export Hospitals Data{% endblock title %}


{% block homepage %}
    <h3>Export Hospitals Data</h3>
    <form action="{% url 'seattle:export-hospitals-data' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Please select the format of the file</p>
        <select name="file-format" class="form-control my-3">
            <option selected>Choose format...</option>
            <option>CSV</option>
            <option>JSON</option>
            <option>XLS (Excel)</option>
        </select>
        <button class="btn btn-primary" type="submit">Export</button>
    </form>

    <a href="{% url 'seattle:index' %}">Return Home View</a><br />
{% endblock homepage %}

django_and_folium/django_and_folium/seattle/templates/seattle/export_library_data.html
{% extends 'base.html' %}

{% block title %}Export Libraries Data{% endblock title %}


{% block homepage %}
    <h3>Export Libraries Data</h3>
    <form action="{% url 'seattle:export-libraries-data' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Please select the format of the file</p>
        <select name="file-format" class="form-control my-3">
            <option selected>Choose format...</option>
            <option>CSV</option>
            <option>JSON</option>
            <option>XLS (Excel)</option>
        </select>
        <button class="btn btn-primary" type="submit">Export</button>
    </form>

    <a href="{% url 'seattle:index' %}">Return Home View</a><br />
{% endblock homepage %}

django_and_folium/django_and_folium/seattle/templates/seattle/export_schools_data.html
{% extends 'base.html' %}

{% block title %}Export Schools Data{% endblock title %}


{% block homepage %}
    <h3>Export Schools Data</h3>
    <form action="{% url 'seattle:export-schools-data' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Please select the format of the file</p>
        <select name="file-format" class="form-control my-3">
            <option selected>Choose format...</option>
            <option>CSV</option>
            <option>JSON</option>
            <option>XLS (Excel)</option>
        </select>
        <button class="btn btn-primary" type="submit">Export</button>
    </form>

    <a href="{% url 'seattle:index' %}">Return Home View</a><br />
{% endblock homepage %}

django_and_folium/django_and_folium/seattle/templates/seattle/import_hospitals_data.html
{% extends 'base.html' %}

{% block title %}Import Hospitals Data{% endblock title %}


{% block content %}
    <h3>Import Hospitals Data</h3>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert {{ message.tags }}"{% endif %}>{{ message }}</li><br>
        Click <a href="{% url 'seattle:index' %}">here</a> to view the full map
        {% endfor %}
    </ul>
    {% endif %}
    <form class="mt-3" action="{% url 'seattle:import-hospitals-data' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="importData">
        <p>Please select the format of the file</p>
        <select name="file-format" class="form-control my-3">
            <option selected>Choose format...</option>
            <option>CSV</option>
            <option>JSON</option>
            <option>XLS (Excel)</option>
        </select>
        <button class="btn btn-primary" type="submit">Import</button>
    </form>

    <a href="{% url 'seattle:index' %}">Return Home View</a><br />
{% endblock content %}

django_and_folium/django_and_folium/seattle/templates/seattle/import_library_data.html
{% extends 'base.html' %}

{% block title %}Import Libraries Data{% endblock title %}


{% block homepage %}
    <h3>Import Libraries Data</h3>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert {{ message.tags }}"{% endif %}>{{ message }}</li><br>
        Click <a href="{% url 'seattle:index' %}">here</a> to view the full map
        {% endfor %}
    </ul>
    {% endif %}
    <form class="mt-3" action="{% url 'seattle:import-libraries-data' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="importData">
        <p>Please select the format of the file</p>
        <select name="file-format" class="form-control my-3">
            <option selected>Choose format...</option>
            <option>CSV</option>
            <option>JSON</option>
            <option>XLS (Excel)</option>
        </select>
        <button class="btn btn-primary" type="submit">Import</button>
    </form>

    <a href="{% url 'seattle:index' %}">Return Home View</a><br />
{% endblock homepage %}

django_and_folium/django_and_folium/seattle/templates/seattle/import_schools_data.html
{% extends 'base.html' %}

{% block title %}Import Schools Data{% endblock title %}


{% block content %}
    <h3>Import Schools Data</h3>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert {{ message.tags }}"{% endif %}>{{ message }}</li><br>
        Click <a href="{% url 'seattle:index' %}">here</a> to view the full map
        {% endfor %}
    </ul>
    {% endif %}
    <form class="mt-3" action="{% url 'seattle:import-schools-data' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="importData">
        <p>Please select the format of the file</p>
        <select name="file-format" class="form-control my-3">
            <option selected>Choose format...</option>
            <option>CSV</option>
            <option>JSON</option>
            <option>XLS (Excel)</option>
        </select>
        <button class="btn btn-primary" type="submit">Import</button>
    </form>

    <a href="{% url 'seattle:index' %}">Return Home View</a><br />
{% endblock content %}